/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef SUNXI_SERIAL_MEMMAP_H
#define SUNXI_SERIAL_MEMMAP_H

#define SUNXI_UART0_BASE		0x02500000
#define SUNXI_UART1_BASE		(SUNXI_UART0_BASE + 0x400)
#define SUNXI_UART2_BASE		(SUNXI_UART0_BASE + 0x800)
#define SUNXI_UART3_BASE		(SUNXI_UART0_BASE + 0xc00)
#define SUNXI_R_UART_BASE		0

#endif /* SUNXI_SERIAL_MEMMAP_H */
